# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install
    - run: npm run compile
    - run: npm run test_report
    - name: Create Test Report Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: test-report
        path: ./mochawesome-report
        retention-days: 3
    env:
      CC_SECRET: ${{ secrets.CC_SECRET }}
      CI: true
  GasReport:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install
    - run: npm run compile
    - run: npm run gas_report
    - run: npx codechecks codechecks.yml
    env:
      CC_SECRET: ${{ secrets.CC_SECRET }}
      CI: true